### ISSUE TITLE
ConnectionStrings Exposed.

### ISSUE THREAD

**Issue by imtiyaz786** [Venureddyyvr/EmployeeAPI#1]
In EmployeeDAL.cs and Department dal.cs, you are using hard-coded connection strings which should be eliminated. It leaves security vulnerabilities in your code. Please let me fix this issue. I can work on it.

**Comment by Venureddyyvr** [comment]
thank you for helping me i have fixed the issue

**Comment by imtiyaz786** [comment]
Glad, I could help you.
